### ISSUE TITLE
Port too High?

### ISSUE THREAD

**Issue by SealsRock12** [r58Playz/astrocraft-python#4]
```python
$ python main.py
2019-08-28 20:52:04 [MainThread] [INFO] Mod loader has identified 0 mods to load
Traceback (most recent call last):
  File "C:\Users\Aneesh.NewPC\Documents\Astrocraft\astrocraft-python\controllers.py", line 226, in setup
    start_server(internal=True)
  File "C:\Users\Aneesh.NewPC\Documents\Astrocraft\astrocraft-python\server.py", line 231, in start_server
    server = Server((localip, 150496), ServerPlayer) #min 100000 max 1000000
  File "C:\Users\Aneesh.NewPC\Documents\Astrocraft\astrocraft-python\server.py", line 199, in __init__
    socketserver.ThreadingTCPServer.__init__(self, *args, **kwargs)
  File "C:\Users\Aneesh.NewPC\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\Aneesh.NewPC\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OverflowError: getsockaddrarg: port must be 0-65535.
```
I was trying to create a Windows install using C++

**Comment by r58Playz** [comment]
Fixing...
